# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeChart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='both_eye_score',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='left_eye_score',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='right_eye_score',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
