# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeChart', '0002_auto_20180325_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
