# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EyeChart', '0005_auto_20180325_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='right_eye_score',
            new_name='AL_OD',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='left_eye_score',
            new_name='AL_OS',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='both_eye_score',
            new_name='AL_OU',
        ),
    ]
