# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeChart', '0006_auto_20180325_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='H_OD',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='H_OS',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='H_OU',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
